name: deproy-pr

# トリガー
on:
  pull_request: #プルリク作成時
    paths: # app以下のディレクトリに変更があった場合に発動
      - "app/**"
      - .github/workflows/deploy-pr.yml # 確認用
env:
  REGISTRY: ghcr.io

#実行されるjob
jobs:
  build-and-push-image: # jobのID
    runs-on: ubuntu-latest # jobが実行される環境
    steps:
      - name: Checkout repository # リポジトリのファイルにアクセス
        uses: actions/checkout@v4 # 参照 -> https://github.com/actions/checkout

      - name: Docker meta # githubのメタ情報を取得
        id: meta
        uses: docker/metadata-action@v5 # 参照 -> https://github.com/docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }} # workflowが実行されるレポジトリ

      - name: Log in to Github Container Registory #Github Container Registoryをイメージレジストリとして使用
        uses: docker/login-action@v3 # 参照 -> https://github.com/docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # トリガーを実行したGithubユーザー
          password: ${{ secrets.GITHUB_TOKEN }} # workflow開始時にトークンを自動発行

      - name: Build and push
        uses: docker/build-push-action@v5 #参照 -> https://github.com/docker/build-push-action
        with:
          context: app # Dockerfileのビルドコンテキスト
          push: true # ghcrにプッシュを実行
          tags: ${{ steps.meta.outputs.tags }} # コンテナイメージのタグ
          labels: ${{ steps.meta.outputs.labels }}
